# Generated by Django 4.0.5 on 2022-06-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='jop',
            new_name='job',
        ),
    ]
